import sys
import json
from slack.deploy import validate_demo_files

with open('sessions/ab423812.json') as f:
    session = json.load(f)

# The generated files that `run_demo` normally passes to deploy are reconstructed here
files = {
    "main.py": "print('hello')\nPORT=8000\n",
    "requirements.txt": "fastapi==0.100.0\nuvicorn==0.23.0\n",
    "Procfile": "web: uvicorn main:app",
}
            
# extract the data files from the demo spec
demo_spec = session["stage_2_design"].get("demo_spec", {})
data_files = demo_spec.get("data_files", [])

# Find the exact content that failed (which is recorded in logs but we don't have the explicit payload 
# stored in the session except as instructions to the LLM. Wait, if it failed validate_demo_files, 
# it was generated by LLM but not committed to github/db because it exception'd out.)

# I will recreate a simulated broken file structure to test validate_demo_files
broken_json = """
[
  {
    "id": "c001",
    "name": "Elite Electrical Solutions",
    "trade": "electrical"
  },
  {
    "id": "c029",
    "name": "Guardian Roofing Systems",
    "trade": "roofing",
    "recent_
"""

files["data/contractors.json"] = broken_json

try:
    warnings = validate_demo_files(files)
    print("SUCCESS!")
    print("Warnings:", warnings)
    print("Fixed JSON content length:", len(files["data/contractors.json"]))
except Exception as e:
    print("FAILED ALGORITHM:", type(e).__name__, e)
    sys.exit(1)
